version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: payroll-app
    container_name: payroll-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payroll
      MYSQL_USER: payroll
      MYSQL_PASSWORD: payroll
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "1000:6379"

volumes:
  db_data:
